name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the version compatible with your project

    - name: Install dependencies
      run: npm install

    - name: Build the website
      run: npm run build # Ensure you have a build script in your package.json that runs your gulp tasks


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
    
    - name: Push changes in output folder to main branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email ""
